[package]
name = "tokio-benchmark"
version = "0.1.0"
authors = ["Yuki Toyoda <toyoda_yuki@cyberagent.co.jp>"]

[dependencies]
tokio = "0.1.11"
http = "0.1"
httparse = "1.0"
bytes = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
time = "0.1"